// doc/src/app/documentation/quick-start-solid/page.js
import { H1, H2, P, Note, Code } from "@/Shared/DocsUI";

export const metadata = { title: "GClass - Quick start (Solid)" };

export default function Page() {
  return (
    <article>
      <H1>Quick start - Solid</H1>
      <P>
        Solid has no VDOM — DOM nodes persist via fine-grained signals. Call{" "}
        <code>initAnimations()</code> in <code>onMount</code>. No <code>afterEach</code> needed unless you use <code>@solidjs/router</code> — then re-init on route or reuse the same watcher as Vue.
      </P><H2>Usage - Solid component</H2>
      <Code>{`import { onMount } from 'solid-js'
import { initAnimations } from 'gclass-anims'

function App() {
  onMount(() => initAnimations())
  return <div class="appear scroll spawn-up">hello solid</div>
}`}</Code>

      <H2>Usage - With router</H2>
      <Code>{`import { Router, Route } from '@solidjs/router'
import { onMount } from 'solid-js'
import { initAnimations } from 'gclass-anims'

function Home() { onMount(() => initAnimations()); return <div class="spawn-up">home</div> }
function About() { onMount(() => initAnimations()); return <div class="spawn-up">about</div> }

export default () => (
  <Router>
    <Route path="/" component={Home} />
    <Route path="/about" component={About} />
  </Router>
)`}</Code>
    </article>
  );
}

// doc/src/app/documentation/quick-start-qwik/page.js
import { H1, H2, P, Note, Code } from "@/Shared/DocsUI";

export const metadata = { title: "GClass - Quick start (Qwik)" };

export default function Page() {
  return (
    <article>
      <H1>Quick start - Qwik</H1>
      <P>
        Qwik is resumable — no hydration replay. Use{" "}
        <code>useVisibleTask$</code> (client only), not <code>useTask$</code> (runs on server before DOM is visible, <code>gsap.fromTo</code> gets no rect).
      </P><H2>Usage - Qwik City page</H2>
      <Code>{`import { component$, useVisibleTask$ } from '@builder.io/qwik'
import { initAnimations } from 'gclass-anims'

export default component$(() => {
  useVisibleTask$(() => {
    initAnimations()
  })
  return <div class="appear scroll spawn-up">hello qwik</div>
})`}</Code>

      <H2>Per-page re-init</H2>
      <P>
        Qwik City does not replay root — each route component needs its own{" "}
        <code>useVisibleTask$</code> re-init, same as SvelteKit <code>afterNavigate</code>.
      </P>
      <Code>{`// src/routes/about/index.tsx
import { component$, useVisibleTask$ } from '@builder.io/qwik'
import { initAnimations } from 'gclass-anims'
export default component$(() => {
  useVisibleTask$(() => initAnimations())
  return <div class="spawn-up">about</div>
})`}</Code>
    </article>
  );
}
