// doc/src/app/documentation/quick-start-lit/page.js
import { H1, H2, P, Note, Code } from "@/Shared/DocsUI";

export const metadata = { title: "GClass - Quick start (Lit)" };

export default function Page() {
  return (
    <article>
      <H1>Quick start - Lit</H1>
      <P>
        Lit defaults to Shadow DOM — <code>Listeners.js:101 qAll</code> queries{" "}
        <code>document</code>, not <code>shadowRoot</code>, so classes inside a{" "}
        <code>LitElement</code> template do not animate unless you opt-out or scope.
      </P><H2>Usage - Light DOM (recommended)</H2>
      <Code>{`import { LitElement, html } from 'lit'
import { initAnimations } from 'gclass-anims'

class MyEl extends LitElement {
  createRenderRoot() { return this } // ← opt out of shadow
  firstUpdated() { initAnimations() }
  render() { return html\`<div class="appear scroll spawn-up">hello lit</div>\` }
}
customElements.define('my-el', MyEl)`}</Code>

      <H2>Usage - Keep Shadow DOM</H2>
      <Code>{`import { LitElement, html } from 'lit'
import initListeners from 'gclass-anims/Listeners.js'

class MyEl extends LitElement {
  firstUpdated() {
    // scope to shadowRoot — global initAnimations() misses it
    initListeners(this.shadowRoot)
  }
  render() { return html\`<div class="spawn-up">hello shadow</div>\` }
}
// slotted light-DOM content *does* animate with global initAnimations()
 // <my-el><span class="spawn-up">slotted — works</span></my-el>`}</Code>
    </article>
  );
}

// doc/src/app/documentation/quick-start-solid/page.js
import { H1, H2, P, Note, Code } from "@/Shared/DocsUI";

export const metadata = { title: "GClass - Quick start (Solid)" };

export default function Page() {
  return (
    <article>
      <H1>Quick start - Solid</H1>
      <P>
        Solid has no VDOM — DOM nodes persist via fine-grained signals. Call{" "}
        <code>initAnimations()</code> in <code>onMount</code>. No <code>afterEach</code> needed unless you use <code>@solidjs/router</code> — then re-init on route or reuse the same watcher as Vue.
      </P><H2>Usage - Solid component</H2>
      <Code>{`import { onMount } from 'solid-js'
import { initAnimations } from 'gclass-anims'

function App() {
  onMount(() => initAnimations())
  return <div class="appear scroll spawn-up">hello solid</div>
}`}</Code>

      <H2>Usage - With router</H2>
      <Code>{`import { Router, Route } from '@solidjs/router'
import { onMount } from 'solid-js'
import { initAnimations } from 'gclass-anims'

function Home() { onMount(() => initAnimations()); return <div class="spawn-up">home</div> }
function About() { onMount(() => initAnimations()); return <div class="spawn-up">about</div> }

export default () => (
  <Router>
    <Route path="/" component={Home} />
    <Route path="/about" component={About} />
  </Router>
)`}</Code>
    </article>
  );
}
